version: '3.9'

services:
  web:
    build:
      context: .
    working_dir: /srv/app
    environment:
      TERM: Linux
    volumes:
      - ./app:/srv/app
      - ./.docker/php/development:/usr/local/etc/php
    ports:
      - "8765:8765"
    command: sh -c "bin/cake server -H 0.0.0.0"

  db:
    image: mysql:latest
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cakephp
      MYSQL_USER: cakephp 
      MYSQL_PASSWORD: cakephp
      MYSQL_ROOT_PASSWORD: root

  composer:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: cake-composer
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    entrypoint: ['composer', '--ignore-platform-reqs']

volumes:
  data:

