version: '3.9'

services:
  php:
    build:
      context: .
    env_file:
      - ./.docker/php.env.development
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./app:/srv/app
         #- ./.docker/php/development:/usr/local/etc/php
         #- ~/.ssh/:/home/root/.ssh
  #   depends_on:
  #     - db

  # db:
  #   image: library/mysql:8
  #   command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   env_file:
  #     - ./.docker/mysql.env.development
  #   volumes:
  #     - data:/var/lib/mysql
  #   ports:
  #     - "3307:3306"

  # web:
  #   image: nginx:1.19-alpine
  #   working_dir: /srv/app/
  #   environment:
  #     TERM: Linux
  #   volumes:
  #     - ./app:/srv/app
  #     - ./.docker/nginx:/etc/nginx/conf.d
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - php
  composer:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: cake-composer
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    entrypoint: ['composer', '--ignore-platform-reqs']

volumes:
  data:
